branch-defaults:
  master:
    environment: Textfabrik-prod-env-php82-env
environment-defaults:
  Textfabrik-prod-env-php82-env:
    branch: null
    repository: null
global:
  application_name: Texthub-prod-env-php8.2
  default_ec2_keyname: texthub
  default_platform: PHP 8.2 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
